name: Pull request

on: create

jobs:
  validate:
    name: Validate pull request
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Create sync pull request
        id: create-sync-pr
        run: |
          gh pr create --draft --base $FROM_BRANCH --head $TO_BRANCH --title "chore: release preview sample" --body "Release preview sample"
        env:
          GH_TOKEN: ${{ steps.generate_token.outputs.token }}
          FROM_BRANCH: "main"
          TO_BRANCH: ${{ github.ref }}

      - name: Release Preview
        uses: haully/semantic-release-preview@1.0.9
